"""
backend/crypto.py
─────────────────
Fernet symmetric encryption helper for tenant OAuth tokens.

Usage:
  from backend.crypto import encrypt_token, decrypt_token

  blob = encrypt_token({"access_token": "xoxb-...", "refresh_token": "..."})
  original = decrypt_token(blob)

The master key is read once from the environment variable KGF_ENCRYPTION_KEY
(a URL-safe base64-encoded 32-byte key generated by Fernet.generate_key()).

If the key is missing (local dev without .env), we fall back to a hardcoded
dev-only key so the app still boots — this key must NEVER reach production.
"""

import os
import json
import base64
import secrets
from cryptography.fernet import Fernet, InvalidToken

# ── Key resolution ────────────────────────────────────────────────────────────
_DEV_FALLBACK_KEY = b"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="  # 32 zero-bytes b64

def _load_key() -> bytes:
    raw = os.getenv("KGF_ENCRYPTION_KEY", "").strip()
    if raw:
        return raw.encode()
    # Dev fallback — log a loud warning so it is never silently used in prod
    import sys
    print(
        "⚠️  WARNING: KGF_ENCRYPTION_KEY is not set. Using insecure dev-only "
        "fallback key. Set this variable before handling real customer tokens.",
        file=sys.stderr,
    )
    return _DEV_FALLBACK_KEY


_fernet = Fernet(_load_key())


# ── Public API ────────────────────────────────────────────────────────────────

def encrypt_token(token_dict: dict) -> bytes:
    """
    Serialize token_dict to JSON and encrypt with Fernet.
    Returns raw bytes suitable for storage in a BYTEA column.
    """
    plaintext = json.dumps(token_dict).encode("utf-8")
    return _fernet.encrypt(plaintext)


def decrypt_token(encrypted: bytes) -> dict:
    """
    Decrypt a Fernet blob and deserialize to dict.
    Raises InvalidToken if the ciphertext was tampered with.
    """
    plaintext = _fernet.decrypt(encrypted)
    return json.loads(plaintext.decode("utf-8"))


def generate_new_key() -> str:
    """
    Helper to generate a fresh Fernet key.
    Run once and paste the output into your .env file:
      python -c "from backend.crypto import generate_new_key; print(generate_new_key())"
    """
    return Fernet.generate_key().decode()
